import { env } from '$env/dynamic/private';
import { createHash } from 'node:crypto';

const ndUrl = env.NAVIDROME_URL;
const ndUser = env.NAVIDROME_USERNAME;
const ndPass = env.NAVIDROME_PASSWORD;

const CLIENT_NAME = 'Endpoint';
const API_VERSION = '1.16.1';

/**
 * Generates Subsonic authentication parameters.
 * Uses legacy token authentication: t = md5(password + salt)
 */
const getAuthParams = () => {
    if (!ndUser || !ndPass) return '';

    // Generate a random salt (6 chars is enough)
    const salt = Math.random().toString(36).substring(2, 8);
    // Calculate token = md5(password + salt)
    const token = createHash('md5').update(ndPass + salt).digest('hex');

    return `u=${encodeURIComponent(ndUser)}&t=${token}&s=${salt}&v=${API_VERSION}&c=${CLIENT_NAME}&f=json`;
};

/**
 * Helper to perform authenticated requests to Subsonic API.
 */
const request = async (endpoint: string, queryParams: Record<string, string> = {}): Promise<any | null> => {
    if (!ndUrl) return null;

    const auth = getAuthParams();
    const qs = new URLSearchParams(queryParams).toString();
    const url = `${ndUrl}/rest/${endpoint}.view?${auth}&${qs}`;

    try {
        const res = await fetch(url);
        if (!res.ok) {
            console.error(`Subsonic request failed: ${res.status}`);
            return null;
        }

        const data = await res.json();
        const response = data['subsonic-response'];

        if (response.status === 'failed') {
            console.error(`Subsonic API error: ${response.error?.message} (code ${response.error?.code})`);
            return null;
        }

        return response;
    } catch (err) {
        console.error('Subsonic request error:', err);
        return null;
    }
};

/**
 * Search for a song by title and artist using `search3` endpoint.
 */
export const findSong = async (
    title: string,
    artist: string
): Promise<string | null> => {
    try {
        // Query usually matches everything, so we try "Artist Title"
        const query = `${artist} ${title}`;
        const res = await request('search3', {
            query,
            songCount: '1',
            songOffset: '0'
        });

        if (!res || !res.searchResult3 || !res.searchResult3.song) return null;

        const songs = res.searchResult3.song;
        if (!Array.isArray(songs) || songs.length === 0) return null;

        return songs[0].id;
    } catch (err) {
        console.error('Navidrome findSong error:', err);
        return null;
    }
};

/**
 * Create a share link for a song using `createShare` endpoint.
 */
export const createShareLink = async (
    songId: string,
    description: string = 'Generated by Endpoint'
): Promise<string | null> => {
    try {
        // expiry in an hour
        const expires = (Date.now() + 60 * 60 * 1000).toString();

        const res = await request('createShare', {
            id: songId,
            description,
            expires
        });

        if (!res || !res.shares || !res.shares.share) return null;

        // share key contains an array of shares, we take the one we just created (usually the last/only one returned?)
        // The API returns the *created* share(s).
        const shares = res.shares.share;
        const share = Array.isArray(shares) ? shares[0] : shares;

        // Return only the ID (e.g. "sOmeTh1ng") which is used in the URL.
        // Actually, Subsonic `id` for share might be numeric or string.
        // Navidrome creates shares with a short alphanumeric string usually.
        return share.id;

    } catch (err) {
        console.error('Navidrome createShareLink error:', err);
        return null;
    }
};

export const getShareUrl = (shareId: string): string => {
    // Navidrome share URLs: /share/{id}
    return `${ndUrl}/share/${shareId}`;
}
