image: yusdacra/nix-flake:latest

pages:
  stage: deploy
  script:
    - nix build -L --show-trace
    - nix-shell -p rsync --run "rsync -Lkr result/* public"
  artifacts:
    paths:
    - public
  only:
  - master