image: yusdacra/nix-flake:latest

before_script:
  - . /bin/pre-build.sh

pages:
  stage: deploy
  script:
  - nix build -L --show-trace
  artifacts:
    paths:
    - result
  only:
  - master

after_script:
  - ./bin/post-build.sh