image: yusdacra/nix-flake:latest

variables:
  CACHIX_NAME: yusdacra-website

before_script:
  - . /bin/pre-build.sh

pages:
  stage: deploy
  script:
    - nix build -L --show-trace
    - nix-shell -p rsync --run "rsync -Lkr result/* public"
  artifacts:
    paths:
    - public
  only:
  - master

after_script:
  - . /bin/post-build.sh