image: yusdacra/nix-flake:latest

pages:
  stage: deploy
  script:
    - nix build -L --show-trace
    - mkdir public && cp -r result/* public
    - touch public/.gitkeep
    - ls public
  artifacts:
    paths:
    - public
  only:
  - master