name: build website

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: lixpine
    steps:
      - uses: actions/checkout@v4
        with:
          github-server-url: 'https://git.gaze.systems'
      - uses: https://github.com/cachix/cachix-action@v16
        with:
          name: gazesys-infra
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix show-config
      - run: nix build . -L --show-trace
  deploy:
    runs-on: lixpine
    depends-on: build
    steps:
      - name: trigger deploy
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          curl -X POST "https://git.gaze.systems/api/v1/repos/90008/ark/actions/workflows/deploy.yaml/dispatches" -H "Accept: application/json" -H "Authorization: token $PAT" --json '{"ref": "terra"}'
