name: create archive with lfs

on:
  push:
    tags:
      - '*'

jobs:
  tag:
    runs-on: native
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        lfs: false
    - name: Checkout LFS
      run: |
        function EscapeForwardSlash() { echo "$1" | sed 's/\//\\\//g'; }
        readonly ReplaceStr="EscapeForwardSlash ${{ gitea.repository }}.git/info/lfs/objects/batch"; sed -i "s/\(\[http\)\( \".*\)\"\]/\1\2`$ReplaceStr`\"]/" .git/config
        git config --local lfs.transfer.maxretries 1
        git lfs install --local
        git lfs fetch origin refs/tags/${{ gitea.ref_name }}
        git lfs checkout
    - run: tar czf ../source.tgz --directory=. .
    - run: du -sh ../source.tgz
    - uses: https://gitea.com/actions/gitea-release-action@v1
      with:
        files: |-
          ../source.tgz
